- name: Delete existing config files
  file:
    path: '{{ item }}'
    state: absent
  loop:
  - ~/.zsdhrc

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/roles/common/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - gitconfig
  - zshrc
