- name: Install homebrew packages
  community.general.homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: homebrew cleanup
  command: brew cleanup
